### ISSUE TITLE
NoSuchMethodError in CRDT entity creation

### ISSUE THREAD

**Issue by politrons** [cloudstateio/cloudstate#139]
Trying to create a CRDT entity with this simple code

```
import io.cloudstate.javasupport.EntityId;
import io.cloudstate.javasupport.crdt.CommandHandler;
import io.cloudstate.javasupport.crdt.CrdtEntity;

@CrdtEntity
public class RestConnector {
    private final String entityId;

    public RestConnector(@EntityId String entityId) {
        this.entityId = entityId;
    }

    @CommandHandler
    public Connector.Response getRequest(Connector.RestRequest requestCommand) {
        System.out.println("Request to Connector:" + requestCommand.getUrl());
        return Connector.Response.newBuilder().setResponse("hello connector world").build();
    }

}
```

And Main class

```
public class RestConnectorMain {

    public static void main(String[] args) throws ExecutionException, InterruptedException {
        System.out.println("Hello connector");

        Descriptors.ServiceDescriptor restConnector = Connector.getDescriptor().findServiceByName("RestConnector");
        System.out.println("Coudstate Rest Connector:" + restConnector);
        new CloudState()
                .registerCrdtEntity(
                        RestConnector.class,
                        restConnector)
                .start()
                .toCompletableFuture()
                .get();
    }
}
```

When I run the docker image I always receive the error

```

service> Exception in thread "main" java.lang.NoSuchMethodError: com.google.protobuf.Descriptors$MethodDescriptor.isServerStreaming()Z
service> 	at io.cloudstate.javasupport.impl.ResolvedServiceMethod.outputStreamed(ResolvedServiceMethod.scala:13)
service> 	at io.cloudstate.javasupport.impl.crdt.AnnotationBasedCrdtSupport.$anonfun$x$5$4(AnnotationBasedCrdtSupport.scala:56)
service> 	at io.cloudstate.javasupport.impl.crdt.AnnotationBasedCrdtSupport.$anonfun$x$5$4$adapted(AnnotationBasedCrdtSupport.scala:56)
service> 	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:256)
service> 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
service> 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
service> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
service> 	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:255)
service> 	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:249)
service> 	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
service> 	at scala.collection.TraversableLike.filter(TraversableLike.scala:347)
service> 	at scala.collection.TraversableLike.filter$(TraversableLike.scala:347)
service> 	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
service> 	at io.cloudstate.javasupport.impl.crdt.AnnotationBasedCrdtSupport.getHandlers$1(AnnotationBasedCrdtSupport.scala:56)
service> 	at io.cloudstate.javasupport.impl.crdt.AnnotationBasedCrdtSupport.<init>(AnnotationBasedCrdtSupport.scala:66)
service> 	at io.cloudstate.javasupport.impl.crdt.AnnotationBasedCrdtSupport.<init>(AnnotationBasedCrdtSupport.scala:25)
service> 	at io.cloudstate.javasupport.CloudState.registerCrdtEntity(CloudState.java:135)
service> 	at io.cloudstate.connector.RestConnectorMain.main(RestConnectorMain.java:20)
```

Any idea what's wrong?

Regards

**Comment by viktorklang** [comment]
Sounds like a classpath problem, what version are you running, and did you add any dependency to your project which pulls in protobuf-java?

**Comment by politrons** [comment]
Hi,

The version of cloudstate is 0.4.3 and the rest of dependencies are normal google gRPC

https://github.com/politrons/Akka/blob/connectorService/CloudStateConnectors/pom.xml#L115

Any conflict with those?.

**Comment by viktorklang** [comment]
@politrons Make sure that you're using protobuf-java 3.9.0: https://github.com/protocolbuffers/protobuf/blob/v3.9.0/java/core/src/main/java/com/google/protobuf/Descriptors.java#L2040

**Comment by politrons** [comment]
Yep, that was the problem, adding 

      ```
  <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.9.0</version>
        </dependency>
```

Fix the issue, thanks
