### ISSUE TITLE
if user-function.desc namespace does not match the one in user function: null ptr excetion

### ISSUE THREAD

**Issue by coreyauger** [cloudstateio/cloudstate#202]
Ok so this is what you see if your user-function.desc does not match the namespace that you put in your user code.. eg:
```
const cloudstate = new Stateless(
    "shop.proto",
    "cloudstate.samples.shopping.frontend.Shop"    
);
```

But you copied over a project that has an already compiled namespace that is different.  This is of course an error on the users part.. but right now it resolves as a nullptr exception:
```
I 2020-03-05T16:55:14.230222423Z 2020-03-05 16:55:14.229 ERROR akka.actor.OneForOneStrategy - null
I 2020-03-05T16:55:14.230613656Z java.lang.NullPointerException
	at io.cloudstate.proxy.EntityTypeSupportFactory.build(UserFunctionTypeSupport.scala:32)
	at io.cloudstate.proxy.EntityDiscoveryManager$$anonfun$receive$1.$anonfun$applyOrElse$1(EntityDiscoveryManager.scala:232)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at io.cloudstate.proxy.EntityDiscoveryManager$$anonfun$receive$1.applyOrElse(EntityDiscoveryManager.scala:223)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at io.cloudstate.proxy.EntityDiscoveryManager.aroundReceive(EntityDiscoveryManager.scala:140)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
I 2020-03-05T16:55:14.457857670Z 2020-03-05 16:55:14.457 DEBUG io.cloudstate.proxy.HealthCheckReady - Error performing warmup readiness check
I 2020-03-05T16:55:14.458485839Z 2020-03-05 16:55:14.457 DEBUG io.cloudstate.proxy.HealthCheckReady - Error performing server manager readiness check```

**Comment by viktorklang** [comment]
This should do it: https://github.com/cloudstateio/cloudstate/pull/203
