### ISSUE TITLE
sbt docs/paradox failed with jsdoc: command not found

### ISSUE THREAD

**Issue by tringuyen-yw** [cloudstateio/cloudstate#258]
Trying to generate documentation (to review changes locally) with `sbt docs/paradox` the task failed with the following error:
```
[info] ... many info line skipped ...
[info] Main Java API documentation successful.
[info] > cloudstate@0.0.3 jsdoc /Users/tri/Documents/CloudStateOpenSource/node-support
[info] > jsdoc -c jsdoc.json
[error] sh: jsdoc: command not found
[error] npm ERR! code ELIFECYCLE
[error] npm ERR! syscall spawn
[error] npm ERR! file sh
[error] npm ERR! errno ENOENT
[error] npm ERR! cloudstate@0.0.3 jsdoc: `jsdoc -c jsdoc.json`
[error] npm ERR! spawn ENOENT
[error] npm ERR!
[error] npm ERR! Failed at the cloudstate@0.0.3 jsdoc script.
[error] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[error] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[error] npm ERR! A complete log of this run can be found in:
[error] npm ERR!     /Users/tri/.npm/_logs/2020-04-22T16_36_58_719Z-debug.log
[error] java.lang.RuntimeException: jsdoc failed with return code 1
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at $105e49a5fd0fdda3a664$.$anonfun$docs$4(build.sbt:170)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (docs / Compile / paradox / mappings) jsdoc failed with return code 1
[error] Total time: 3 s, completed 22-Apr-2020 12:36:58 PM
```

**Comment by marcellanz** [comment]
@tringuyen-yw I get the very same error on a freshly cloned repo. But the following sequence makes the command running:

```
$ cd node-support
$ npm install
$ cd ..
$ sbt docs/paradox
```

**Comment by marcellanz** [comment]
@tringuyen-yw the sequence above is documented here:
https://cloudstate.io/docs/developer/thebuild.html#installation-instructions

... many have been run into the same issue and this was added in the documentation.

**Comment by tringuyen-yw** [comment]
@marcellanz Works OK, thanks. Issue fixed.
