### ISSUE TITLE
Native image builds for proxy with cassandra and postgres

### ISSUE THREAD

**Issue by pvlugter** [cloudstateio/cloudstate#331]
I was trying a `dockerBuildAllNative` for the 0.5.1 release, but the proxy-cassandra and proxy-postgres native image builds look like they're missing reflection configuration.

They currently start with this error:

```
❯ docker run cloudstateio/cloudstate-proxy-native-cassandra
Exception in thread "main" java.lang.IllegalArgumentException: no matching constructor found on class akka.actor.LocalActorRefProvider$Guardian for arguments [class akka.actor.OneForOneStrategy]
    at akka.util.Reflect$.error$1(Reflect.scala:86)
    at akka.util.Reflect$.findConstructor(Reflect.scala:110)
    at akka.actor.ArgsReflectConstructor.<init>(IndirectActorProducer.scala:99)
    at akka.actor.IndirectActorProducer$.apply(IndirectActorProducer.scala:64)
    at akka.actor.Props.producer(Props.scala:131)
    at akka.actor.Props.<init>(Props.scala:144)
    at akka.actor.Props$.apply(Props.scala:86)
    at akka.actor.LocalActorRefProvider$$anon$2.<init>(ActorRefProvider.scala:509)
    at akka.actor.LocalActorRefProvider.rootGuardian$lzycompute(ActorRefProvider.scala:507)
    at akka.actor.LocalActorRefProvider.rootGuardian(ActorRefProvider.scala:506)
    at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:580)
    at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:220)
    at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:49)
    at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1017)
    at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1013)
    at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1013)
    at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1036)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:260)
    at io.cloudstate.proxy.CloudStateProxyMain$.$anonfun$start$1(CloudStateProxyMain.scala:142)
    at scala.Option.fold(Option.scala:251)
    at io.cloudstate.proxy.CloudStateProxyMain$.start(CloudStateProxyMain.scala:142)
    at io.cloudstate.proxy.CloudStateProxyMain$.start(CloudStateProxyMain.scala:131)
    at io.cloudstate.proxy.CloudStateProxyMain$.main(CloudStateProxyMain.scala:128)
    at io.cloudstate.proxy.CloudStateProxyMain.main(CloudStateProxyMain.scala)
```

**Comment by pvlugter** [comment]
Looks like #338 did not resolve this issue. Also reported in #404.
