### ISSUE TITLE
Injector fail with Crdt Type parameter

### ISSUE THREAD

**Issue by sleipnir** [cloudstateio/cloudstate#391]
Hello when investigating the issue https://github.com/cloudstateio/kotlin-support/issues/46 I found that java-support fails when we create a constructor that receives a CRDT type as a parameter.

Constructor:
```
@CrdtEntity
class PresenceEntity(vote: Vote) {
```

```
Exception in thread "main" java.lang.RuntimeException: Don't know how to handle argument of type class java.lang.Class in constructor
        at io.cloudstate.javasupport.impl.crdt.EntityConstructorInvoker.$anonfun$new$1(AnnotationBasedCrdtSupport.scala:276)
        at io.cloudstate.javasupport.impl.crdt.EntityConstructorInvoker.$anonfun$new$1$adapted(AnnotationBasedCrdtSupport.scala:274)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at io.cloudstate.javasupport.impl.crdt.EntityConstructorInvoker.<init>(AnnotationBasedCrdtSupport.scala:274)
        at io.cloudstate.javasupport.impl.crdt.AnnotationBasedCrdtSupport.$anonfun$constructor$1(AnnotationBasedCrdtSupport.scala:68)
        at scala.Option.getOrElse(Option.scala:189)
        at io.cloudstate.javasupport.impl.crdt.AnnotationBasedCrdtSupport.<init>(AnnotationBasedCrdtSupport.scala:66)
        at io.cloudstate.javasupport.impl.crdt.AnnotationBasedCrdtSupport.<init>(AnnotationBasedCrdtSupport.scala:63)
        at io.cloudstate.kotlinsupport.CloudStateRunner.withAllRegisters(CloudstateRunner.kt:43)
        at io.cloudstate.kotlinsupport.CloudstateKt.cloudstate(Cloudstate.kt:15)
        at io.cloudstate.examples.chat.presence.MainKt.main(Main.kt:6)
        at io.cloudstate.examples.chat.presence.MainKt.main(Main.kt)

```

The code that validates the constructor parameters in the java-support library is:

```
private final class EntityConstructorInvoker(constructor: Constructor[_]) extends (CrdtCreationContext => AnyRef) {
  private val parameters =
    ReflectionHelper.getParameterHandlers[CrdtCreationContext](constructor)(CrdtAnnotationHelper.crdtParameterHandlers)
  parameters.foreach {
    case MainArgumentParameterHandler(clazz) =>
      throw new RuntimeException(s"Don't know how to handle argument of type $clazz in constructor")
    case _ =>
  }

  def apply(context: CrdtCreationContext): AnyRef = {
    val ctx = InvocationContext("", context)
    constructor.newInstance(parameters.map(_.apply(ctx)): _*).asInstanceOf[AnyRef]
  }
}
```

Kotlin support 0.5.1 use java-support 0.4.7

**Comment by pvlugter** [comment]
Looks to be a problem just in kotlin-support. Added a fix: https://github.com/cloudstateio/kotlin-support/pull/47

Closing the issue here.
