### ISSUE TITLE
postgres native build produces stacktrace and failure starting

### ISSUE THREAD

**Issue by sdake** [cloudstateio/cloudstate#404]
sdake@scale-cp:~/cloudstate-java-support-0.5.2$ kubectl logs shopping-cart-deployment-c86f7464-8z2xm -c akka-sidecarException in thread "main" java.lang.IllegalArgumentException: no matching constructor found on class akka.actor.LocalActorRefProvider$Guardian for arguments [class akka.actor.OneForOneStrategy]
        at akka.util.Reflect$.error$1(Reflect.scala:89)
        at akka.util.Reflect$.findConstructor(Reflect.scala:113)
        at akka.actor.ArgsReflectConstructor.<init>(IndirectActorProducer.scala:99)
        at akka.actor.IndirectActorProducer$.apply(IndirectActorProducer.scala:64)
        at akka.actor.Props.producer(Props.scala:131)
        at akka.actor.Props.<init>(Props.scala:144)
        at akka.actor.Props$.apply(Props.scala:86)
        at akka.actor.LocalActorRefProvider$$anon$2.<init>(ActorRefProvider.scala:516)
        at akka.actor.LocalActorRefProvider.rootGuardian$lzycompute(ActorRefProvider.scala:514)
        at akka.actor.LocalActorRefProvider.rootGuardian(ActorRefProvider.scala:513)
        at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:587)
        at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:220)
        at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:49)
        at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1017)
        at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1013)
        at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1013)
        at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1036)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:260)
        at io.cloudstate.proxy.CloudStateProxyMain$.$anonfun$start$1(CloudStateProxyMain.scala:140)
        at scala.Option.fold(Option.scala:263)
        at io.cloudstate.proxy.CloudStateProxyMain$.start(CloudStateProxyMain.scala:140)
        at io.cloudstate.proxy.CloudStateProxyMain$.start(CloudStateProxyMain.scala:129)
        at io.cloudstate.proxy.jdbc.CloudStateJdbcProxyMain$.main(CloudStateJdbcProxyMain.scala:25)
        at io.cloudstate.proxy.jdbc.CloudStateJdbcProxyMain.main(CloudStateJdbcProxyMain.scala)

**Comment by pvlugter** [comment]
@sdake, thanks for reporting. The native image builds are not currently tested (other than the dev-mode image). The cassandra native build also fails with the same exception (#331). For now, please use the non-native proxy builds.

**Comment by pvlugter** [comment]
@sdake, assuming you're building the images from source, the latest version on master should be working now. Let us know if there are any further issues.
